default_platform(:ios)

DEVELOPER_APP_ID = "#{ENV["DEVELOPER_APP_ID"]}"
DEVELOPER_APP_IDENTIFIER = "#{ENV["DEVELOPER_APP_IDENTIFIER"]}"
PROVISIONING_PROFILE_SPECIFIER = "#{ENV["PROVISIONING_PROFILE_SPECIFIER"]}"
TEMP_KEYCHAIN_USER = "#{ENV["TEMP_KEYCHAIN_USER"]}"
TEMP_KEYCHAIN_PASSWORD = "#{ENV["TEMP_KEYCHAIN_PASSWORD"]}"

def delete_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("security default-keychain -s ~/Library/Keychains/login.keychain-db")
end

def create_temp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    default_keychain: true,
    unlock: true,
    timeout: 0
  )
end

def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end

platform :ios do
  lane :closed_beta do
    keychain_name = "name"
    keychain_password = "Test@123"
    ensure_temp_keychain(keychain_name, keychain_password)
    match(
      type: 'appstore',
      app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
      git_basic_authorization: Base64.strict_encode64(ENV["GIT_AUTHORIZATION"]),
      readonly: true,
      keychain_name: keychain_name,
      keychain_password: keychain_password 
    )

    gym(
      configuration: "Release",
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: { 
            DEVELOPER_APP_ID => PROVISIONING_PROFILE_SPECIFIER
        }
      }
    )

    pilot(
      apple_id: "#{DEVELOPER_APP_ID}",
      app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
      skip_waiting_for_build_processing: true,
      skip_submission: true,
      distribute_external: false,
      notify_external_testers: false,
      ipa: "./Runner.ipa"
    )

    delete_temp_keychain(keychain_name)
  end
end